#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.


# left empty as not needed on this stage :P ...
echo "==> Nothing to do in cibuild"