#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/.."

# run update before tests
script/update

echo "===> Running tests..."

# run all tests using rake
rake
